### ISSUE TITLE
How to get SVG path of my logo?

### ISSUE THREAD

**Issue by phoenixvk** [JorgeCastilloPrz/AndroidFillableLoaders#13]
How to get SVG path of my logo? Any tutorial available?

**Comment by rohittayal595** [comment]
Open the image in gimp... Trace the path of your logo... Save it externally on hard drive... Then you would need to open this file in a text viewer... Here you'd find the path you previously extracted..

**Comment by rohittayal595** [comment]
http://www.useragentman.com/blog/2013/04/26/how-to-create-svg-paths-easily-using-the-gimp/

This will make it easy to understand :)

**Comment by phoenixvk** [comment]
Thank you so much
