### ISSUE TITLE
Attribute XXXX has been defined

### ISSUE THREAD

**Issue by yavik14** [JorgeCastilloPrz/AndroidFillableLoaders#2]
Hi Jorge,

I use the library but when i make build, AS shows me the message:

Error:(2) Attribute "strokeWidth" has already been defined
Error:(2) Attribute "fillColor" has already been defined
Error:(2) Attribute "strokeColor" has already been defined

I think that the names of these attributes are too generic and conflict with other popular libraries and can not use yours.

 I hope that solutions soon, greetings.

**Comment by JorgeCastilloPrz** [comment]
Hello. It is a known bug and i am going to fix it right now, but i would need to know which library is getting in conflict with those values, so i can be able to reproduce the compilation fail. Could you give me the name of the library?

Thanks in advance.

**Comment by JorgeCastilloPrz** [comment]
Ok, nevermind. It has been fixed and a new version has been released.

```groovy
compile 'com.github.jorgecastilloprz:fillableloaders:1.02@aar'
```

Check out the [Changelog](https://github.com/JorgeCastilloPrz/AndroidFillableLoaders/blob/master/CHANGELOG.md) to get more details about the new custom attribute syntax and more features that have been added to the lib.

Cheers!
