### ISSUE TITLE
Paint overriding

### ISSUE THREAD

**Issue by lassana** [JorgeCastilloPrz/AndroidFillableLoaders#6]
Both `fillPaint` and `initFillPaint` are private. Sometimes changing this paint is really necessary.

For example, at the moment using smth like this from the client code is impossible:

    bitmapShader = new BitmapShader(patternBitmap, Shader.TileMode.REPEAT, Shader.TileMode.REPEAT);
    fillPaint.setShader(bitmapShader);

**Comment by JorgeCastilloPrz** [comment]
That is a very good idea and so simple to fix. I will remember this for the next release version! Thanks for your help 😊
