### ISSUE TITLE
Possible to set fill according to numeric value?

### ISSUE THREAD

**Issue by power7714** [JorgeCastilloPrz/AndroidFillableLoaders#7]
Is is possible to set the fill level based on a numeric value? For example, from 0 to 5. I want to use a specific svg as the loader design but fill it based on the total value of ratings from 0 to 5. Please let me know if this is possible as soon as you can. Thank you.

**Comment by godblessyouandme** [comment]
sorry i don't understand what you said. Could you repeat it in simple world?




------------------ 原始邮件 ------------------
发件人: "Steve Curtis";<notifications@github.com>;
发送时间: 2016年4月28日(星期四) 下午4:43
收件人: "JorgeCastilloPrz/AndroidFillableLoaders"<AndroidFillableLoaders@noreply.github.com>; 

主题: [JorgeCastilloPrz/AndroidFillableLoaders] Possible to set fillaccording to numeric value? (#7)




Is is possible to set the fill level based on a numeric value? For example, from 0 to 5. I want to use a specific svg as the loader design but fill it based on the total value of ratings from 0 to 5. Please let me know if this is possible as soon as you can. Thank you.

**Comment by power7714** [comment]
Okay. Sorry. Currently the loading image is filled by percentage right? Like a progress dialog. 0-100% and then hides once complete. But what if instead I want the maximum value to be 5 and if the value is lets say 3.5, it only fills up to that level. Like a seekbar or progress bar would. For example, if the outline/image is a cup, what if I only want the cup to fill half way but stay visible no matter if the cup is full or not. I hope that better explains what I am trying to achieve. I want it to fill the same way a ratingbar would fill. if the value is only 4.5, it only fills 4 and a half of the 5 stars. I want the same effect but with a cup image using this library, not with stars but not selectable.

**Comment by godblessyouandme** [comment]
Thank you for your patience.I benefit a lot from your words.Your project exceedingly perfect,whith Chinese world is "牛逼"





------------------ 原始邮件 ------------------
发件人: "Steve Curtis";<notifications@github.com>;
发送时间: 2016年4月29日(星期五) 上午6:38
收件人: "JorgeCastilloPrz/AndroidFillableLoaders"<AndroidFillableLoaders@noreply.github.com>; 
抄送: "手心里的空白"<857931091@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [JorgeCastilloPrz/AndroidFillableLoaders] Possible to set fillaccording to numeric value? (#7)




Okay. Sorry. Currently the loading image is filled by percentage right? Like a progress dialog. 0-100% and then hides once complete. But what if instead I want the maximum value to be 5 and if the value is lets say 3.5, it only fills up to that level. Like a seekbar or progress bar would. For example, if the outline/image is a cup, what if I only want the cup to fill half way but stay visible no matter if the cup is full or not. I hope that better explains what I am trying to achieve. I want it to fill the same way a ratingbar would fill. if the value is only 4.5, it only fills 4 and a half of the 5 stars. I want the same effect but with a cup image using this library, not with stars but not selectable.

**Comment by Letme** [comment]
@power7714 why dont you just calculate percentage out of that so 5 = 100% and it is simple as that.

**Comment by JorgeCastilloPrz** [comment]
You can fill up to a given percentage using the brand new percentage feature merged some days ago. Check version 1.03 of the lib. The loader will start getting filled and will stop in the % you picked.

Closing this issue.
